disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_comma #disabling this rule since it leads to better readability in collection literal diffs
opt_in_rules:
    - comma_inheritance
    - conditional_returns_on_newline
    - convenience_type
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - legacy_objc_type
    - multiline_arguments
    - multiline_function_chains
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - weak_delegate
    - xct_specific_matcher
    - yoda_condition
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
function_body_length:
  - 100
  - 150
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 60
    error: 70
  excluded: iPhone # excluded via string
identifier_name:
  min_length: 2
  max_length: 60
trailing_whitespace:
  severity: error
vertical_whitespace:
  severity: error
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)